/**
 * TypeScript configuration validation and generation.
 *
 * Runs after the canonical workspace is assembled and before the build. A
 * TypeScript project with a missing or hostile tsconfig.json cannot be built
 * by Vite on the runner, so CPR either repairs the config or writes a known
 * good one. This module never throws: on any internal failure the caller gets
 * a freshly generated default config.
 */

import type { CprFile, TsconfigResult } from "../types/index.ts";

export const TSCONFIG_PATH = "tsconfig.json";
export const TSCONFIG_NODE_PATH = "tsconfig.node.json";

export function defaultTsconfig(react = true): Record<string, unknown> {
  const compilerOptions: Record<string, unknown> = {
    target: "ES2020",
    useDefineForClassFields: true,
    lib: ["ES2020", "DOM", "DOM.Iterable"],
    module: "ESNext",
    skipLibCheck: true,
    moduleResolution: "bundler",
    allowImportingTsExtensions: true,
    resolveJsonModule: true,
    isolatedModules: true,
    noEmit: true,
    strict: false,
    noUnusedLocals: false,
    noUnusedParameters: false,
    baseUrl: ".",
    paths: { "@/*": ["./src/*"] },
  };
  if (react) compilerOptions.jsx = "react-jsx";
  return { compilerOptions, include: ["src"], exclude: ["node_modules", "dist"] };
}

export function defaultTsconfigNode(): Record<string, unknown> {
  return {
    compilerOptions: {
      composite: true,
      skipLibCheck: true,
      module: "ESNext",
      moduleResolution: "bundler",
      allowSyntheticDefaultImports: true,
    },
  };
}

export function usesTypeScript(files: CprFile[], packageJson: Record<string, unknown>, root = ""): boolean {
  const prefix = root ? `${root.replace(/\/$/, "")}/` : "";
  const deps = {
    ...(packageJson?.dependencies as Record<string, string> ?? {}),
    ...(packageJson?.devDependencies as Record<string, string> ?? {}),
  };
  if (deps.typescript) return true;
  return files.some(
    (f) => f.path.startsWith(`${prefix}src/`) && /\.tsx?$/.test(f.path) && !f.path.endsWith(".d.ts"),
  );
}

function usesAtAlias(files: CprFile[], root = ""): boolean {
  const prefix = root ? `${root.replace(/\/$/, "")}/` : "";
  return files.some(
    (f) =>
      f.path.startsWith(`${prefix}src/`) &&
      /\.(tsx?|jsx?)$/.test(f.path) &&
      /from\s+["']@\/|import\(\s*["']@\//.test(f.content ?? ""),
  );
}

export interface TsconfigOptions {
  root?: string;
  react?: boolean;
  /** Packages installed / declared — used to validate an `extends` package. */
  declaredPackages?: Record<string, string>;
}

export function emptyTsconfigResult(): TsconfigResult {
  return {
    typescriptDetected: false,
    generated: false,
    fixed: false,
    nodeConfigGenerated: false,
    issues: [],
    patches: [],
  };
}

/**
 * Validate, repair, or generate the TypeScript configuration.
 * Returns full replacement contents for every file CPR should write.
 */
export function ensureTypescriptConfig(
  files: CprFile[],
  packageJson: Record<string, unknown>,
  opts: TsconfigOptions = {},
): TsconfigResult {
  const result = emptyTsconfigResult();
  const root = opts.root ?? "";
  const prefix = root ? `${root.replace(/\/$/, "")}/` : "";
  const react = opts.react ?? true;

  const write = (path: string, value: unknown, reason: string) =>
    result.patches.push({ path, content: JSON.stringify(value, null, 2) + "\n", reason });

  try {
    if (!usesTypeScript(files, packageJson, root)) return result;
    result.typescriptDetected = true;

    const existing = files.find((f) => f.path === `${prefix}${TSCONFIG_PATH}`);
    if (!existing?.content) {
      result.generated = true;
      write(`${prefix}${TSCONFIG_PATH}`, defaultTsconfig(react), "TypeScript configuration generated by CPR");
      return result;
    }

    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(stripJsonComments(existing.content));
      if (!parsed || typeof parsed !== "object") throw new Error("not an object");
    } catch {
      result.generated = true;
      result.issues.push("tsconfig.json was malformed and could not be parsed — a fresh configuration was generated.");
      write(`${prefix}${TSCONFIG_PATH}`, defaultTsconfig(react), "Malformed tsconfig.json replaced by CPR");
      return result;
    }

    const issues: string[] = [];

    /* ---- extends ---------------------------------------------------- */
    const ext = parsed.extends;
    if (typeof ext === "string" && ext) {
      const isRelative = ext.startsWith(".") || ext.startsWith("/");
      let ok: boolean;
      if (isRelative) {
        const target = normalizePath(`${prefix}${ext.replace(/^\.\//, "")}`);
        ok = files.some((f) => f.path === target || f.path === `${target}.json`);
      } else {
        const pkg = ext.startsWith("@") ? ext.split("/").slice(0, 2).join("/") : ext.split("/")[0];
        ok = !!(opts.declaredPackages ?? {})[pkg];
      }
      if (!ok) {
        delete parsed.extends;
        issues.push(`extends "${ext}" could not be resolved — the field was removed.`);
      }
    }

    /* ---- compilerOptions -------------------------------------------- */
    const co = { ...((parsed.compilerOptions as Record<string, unknown>) ?? {}) };
    const set = (key: string, to: unknown, from: unknown) => {
      co[key] = to;
      issues.push(`compilerOptions.${key} changed from ${format(from)} to ${format(to)}.`);
    };

    if (react && (co.jsx === undefined || co.jsx === "react")) set("jsx", "react-jsx", co.jsx);
    if (co.moduleResolution === "node" || co.moduleResolution === "classic") {
      set("moduleResolution", "bundler", co.moduleResolution);
    }
    if (typeof co.target === "string" && /^es[35]$/i.test(co.target)) set("target", "ES2020", co.target);
    if (co.skipLibCheck === undefined || co.skipLibCheck === false) set("skipLibCheck", true, co.skipLibCheck);
    if (co.strict === true) set("strict", false, true);
    if (co.noEmit === undefined) set("noEmit", true, undefined);
    if (co.isolatedModules === undefined) set("isolatedModules", true, undefined);

    if (usesAtAlias(files, root)) {
      const paths = { ...((co.paths as Record<string, string[]>) ?? {}) };
      const mapped = paths["@/*"];
      if (!Array.isArray(mapped) || !mapped.includes("./src/*")) {
        paths["@/*"] = ["./src/*"];
        co.paths = paths;
        if (co.baseUrl === undefined) co.baseUrl = ".";
        issues.push('compilerOptions.paths gained the mapping "@/*" → "./src/*".');
      }
    }

    parsed.compilerOptions = co;

    /* ---- references -------------------------------------------------- */
    const refs = Array.isArray(parsed.references) ? (parsed.references as { path?: string }[]) : [];
    const referencesNode = refs.some((r) => typeof r?.path === "string" && r.path.includes(TSCONFIG_NODE_PATH));
    if (referencesNode && !files.some((f) => f.path === `${prefix}${TSCONFIG_NODE_PATH}`)) {
      result.nodeConfigGenerated = true;
      issues.push("tsconfig.node.json was referenced but missing — it was generated.");
      write(`${prefix}${TSCONFIG_NODE_PATH}`, defaultTsconfigNode(), "Referenced tsconfig.node.json generated by CPR");
    }

    if (issues.length) {
      result.fixed = true;
      result.issues = issues;
      write(`${prefix}${TSCONFIG_PATH}`, parsed, "TypeScript configuration corrected by CPR");
    }
    return result;
  } catch (err) {
    // Resilience clause: never crash the pipeline over tsconfig handling.
    const fresh = emptyTsconfigResult();
    fresh.typescriptDetected = true;
    fresh.generated = true;
    fresh.issues = [
      `TypeScript validation failed (${err instanceof Error ? err.message : String(err)}) — a default configuration was generated.`,
    ];
    fresh.patches = [
      {
        path: `${prefix}${TSCONFIG_PATH}`,
        content: JSON.stringify(defaultTsconfig(react), null, 2) + "\n",
        reason: "Default TypeScript configuration generated after validation failure",
      },
    ];
    return fresh;
  }
}

function format(v: unknown): string {
  return v === undefined ? "unset" : JSON.stringify(v);
}

function normalizePath(p: string): string {
  const out: string[] = [];
  for (const part of p.split("/")) {
    if (!part || part === ".") continue;
    if (part === "..") out.pop();
    else out.push(part);
  }
  return out.join("/");
}

function stripJsonComments(input: string): string {
  return input
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:"'\\])\/\/[^\n]*/g, "$1")
    .replace(/,(\s*[}\]])/g, "$1");
}
