// Shared utilities and files for all Android project generators

import type { GeneratedIcon } from "@/lib/iconGenerator";

export interface GeneratorConfig {
  appName: string;
  packageName: string;
  url?: string; // For URL-to-app mode
  webFiles?: Map<string, string | ArrayBuffer>; // For upload mode: path -> content
  enabledPlugins?: string[];
  versionCode?: number;
  versionName?: string;
  icons?: GeneratedIcon[]; // Generated icon data
}

export interface GeneratedFile {
  path: string;
  content: string | ArrayBuffer;
  isBinary?: boolean;
}

// ─── Gradle Wrapper ────────────────────────────────────────

export const gradleWrapperProperties = () =>
`distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-all.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`;

export const gradlewScript = () =>
`#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=\`ls -ld "$PRG"\`
    link=\`expr "$ls" : '.*-> \\(.*\\)$'\`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=\`dirname "$PRG"\`"/$link"
    fi
done
SAVED="\`pwd\`"
cd "\`dirname \\"$PRG\\"\`/" >/dev/null
APP_HOME="\`pwd -P\`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=\`basename "$0"\`

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \\
  "-Dorg.gradle.appname=$APP_BASE_NAME" \\
  -classpath "$CLASSPATH" \\
  org.gradle.wrapper.GradleWrapperMain "$@"
`;

export const gradlewBatScript = () =>
`@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome
set JAVA_EXE=java.exe
goto execute

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe
goto execute

:execute
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" endlocal

:omega
`;

export const gradleProperties = () =>
`# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
`;

export const localProperties = () =>
`# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
# Location of the SDK. This is only used by Gradle.
# sdk.dir=/Users/USERNAME/Library/Android/sdk
`;

export const proguardRules = () =>
`# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /sdk/tools/proguard/proguard-android.txt

# Keep JavaScript interface methods
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# If using Capacitor
-keep class com.getcapacitor.** { *; }
-keep class org.apache.cordova.** { *; }
`;

export const stringsXml = (appName: string, packageName?: string) =>
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${appName}</string>
    <string name="title_activity_main">${appName}</string>
    <string name="package_name">${packageName || appName.toLowerCase().replace(/\s+/g, '.')}</string>
    <string name="custom_url_scheme">${packageName || appName.toLowerCase().replace(/\s+/g, '.')}</string>
</resources>
`;

export const filePathsXml = () =>
`<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path name="my_images" path="." />
    <cache-path name="my_cache_images" path="." />
    <files-path name="my_files" path="." />
</paths>
`;

// Minimal valid 1x1 transparent PNG - generated as raw bytes (no atob needed)
const createPlaceholderPng = (): ArrayBuffer => {
  // Pre-computed bytes for a valid 1x1 transparent PNG
  const pngBytes = new Uint8Array([
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
    0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR chunk
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // 1x1
    0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, // RGBA, filters
    0x00, 0x00, 0x00, 0x0A, 0x49, 0x44, 0x41, 0x54, // IDAT chunk
    0x78, 0x9C, 0x62, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0xE5, // compressed data
    0x27, 0xDE, 0xFC,
    0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, // IEND chunk
    0xAE, 0x42, 0x60, 0x82,
  ]);
  return pngBytes.buffer;
};

export const splashDrawable = () =>
`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" />
</layer-list>
`;

// Common files every Android project needs
export const getSharedFiles = (config: GeneratorConfig): GeneratedFile[] => {
  const files: GeneratedFile[] = [
    { path: "gradle/wrapper/gradle-wrapper.properties", content: gradleWrapperProperties() },
    { path: "gradlew", content: gradlewScript() },
    { path: "gradlew.bat", content: gradlewBatScript() },
    { path: "gradle.properties", content: gradleProperties() },
    { path: "local.properties", content: localProperties() },
    { path: "app/proguard-rules.pro", content: proguardRules() },
    { path: "app/src/main/res/values/strings.xml", content: stringsXml(config.appName, config.packageName) },
    { path: "app/src/main/res/xml/file_paths.xml", content: filePathsXml() },
    { path: "app/src/main/res/drawable/splash_screen.xml", content: splashDrawable() },
    { path: `README.md`, content: generateReadme(config) },
  ];

  // Add icon files if provided, otherwise generate a default adaptive icon
  if (config.icons && config.icons.length > 0) {
    for (const icon of config.icons) {
      files.push({
        path: `app/src/main/res/${icon.folder}/ic_launcher.png`,
        content: icon.squareBlob,
        isBinary: true,
      });
      files.push({
        path: `app/src/main/res/${icon.folder}/ic_launcher_round.png`,
        content: icon.roundBlob,
        isBinary: true,
      });
    }
  } else {
    // Generate fallback PNG icons in all density folders so @mipmap/ic_launcher resolves on all API levels
    const placeholderPng = createPlaceholderPng();
    const densityFolders = ["mipmap-mdpi", "mipmap-hdpi", "mipmap-xhdpi", "mipmap-xxhdpi"];
    for (const folder of densityFolders) {
      files.push({ path: `app/src/main/res/${folder}/ic_launcher.png`, content: placeholderPng, isBinary: true });
      files.push({ path: `app/src/main/res/${folder}/ic_launcher_round.png`, content: placeholderPng, isBinary: true });
    }

    // Also keep adaptive icon XMLs for API 26+
    const defaultIconXml = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/colorPrimary"/>
    <foreground android:drawable="@color/colorPrimary"/>
</adaptive-icon>
`;
    files.push({ path: "app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml", content: defaultIconXml });
    files.push({ path: "app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml", content: defaultIconXml });
  }

  return files;
};

const generateReadme = (config: GeneratorConfig) =>
`# ${config.appName}

Android project generated by MobileForge.

## Build Instructions

1. Open this project in Android Studio (Hedgehog or newer)
2. Wait for Gradle sync to complete
3. Connect a device or start an emulator (API 24+)
4. Click Run ▶️

## Configuration

- **Package:** \`${config.packageName}\`
- **Min SDK:** 24 (Android 7.0)
- **Target SDK:** 34
- **Compile SDK:** 34

Generated by MobileForge — https://mobileforge.dev
`;
