import { PLATFORM_CAPACITOR_MAJOR, PLATFORM_NODE_VERSION, PLATFORM_RELEASE } from "../versions/index.ts";

/**
 * Canonical file templates.
 *
 * Every file the canonical project must always have, regardless of what the
 * user uploaded. Nothing here is project specific — all variance arrives via
 * arguments so the same template renders for any input.
 */

export const CAPACITOR_DEPENDENCIES: Record<string, string> = {
  "@capacitor/core": `^${PLATFORM_CAPACITOR_MAJOR}.0.0`,
  "@capacitor/app": `^${PLATFORM_CAPACITOR_MAJOR}.0.0`,
};

export const CAPACITOR_DEV_DEPENDENCIES: Record<string, string> = {
  "@capacitor/cli": `^${PLATFORM_CAPACITOR_MAJOR}.0.0`,
};

export const NATIVE_FLAG_PATH = "src/nativeforge.ts";

export function nativeFlagFile(): string {
  return `/**
 * Generated by NativeForge CPR. Do not edit — regenerated on every CPR run.
 *
 * Import this anywhere to branch on native vs browser rendering:
 *   import { NATIVEFORGE_NATIVE, NATIVEFORGE_PLATFORM } from "@/nativeforge";
 */
export const NATIVEFORGE_NATIVE = true;

export const NATIVEFORGE_PLATFORM: "android" | "ios" | "electron" | "web" =
  typeof navigator !== "undefined" && /android/i.test(navigator.userAgent)
    ? "android"
    : typeof navigator !== "undefined" && /iphone|ipad|ipod/i.test(navigator.userAgent)
      ? "ios"
      : "web";

/** True only when the app is running inside a real browser tab. */
export const NATIVEFORGE_WEB = !NATIVEFORGE_NATIVE;
`;
}

export function capacitorConfig(opts: {
  appId: string;
  appName: string;
  webDir: string;
}): string {
  return `import type { CapacitorConfig } from '@capacitor/cli';

// Generated by NativeForge CPR — regenerated on every run.
const config: CapacitorConfig = {
  appId: ${JSON.stringify(opts.appId)},
  appName: ${JSON.stringify(opts.appName)},
  webDir: ${JSON.stringify(opts.webDir)},
  server: {
    androidScheme: 'https',
  },
};

export default config;
`;
}

export function viteConfig(opts: {
  framework: string;
  pluginImports: string[];
  pluginCalls: string[];
  outDir: string;
}): string {
  const imports = ["import { defineConfig } from 'vite';", ...opts.pluginImports].join("\n");
  return `${imports}

// Generated by NativeForge CPR — relative base is required for file:// WebView loads.
export default defineConfig({
  base: './',
  plugins: [${opts.pluginCalls.join(", ")}],
  resolve: {
    // Extensionless imports must resolve even when a project was partially
    // migrated from JavaScript to TypeScript.
    extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
  },
  build: {
    outDir: ${JSON.stringify(opts.outDir)},
    assetsDir: 'assets',
    emptyOutDir: true,
    sourcemap: false,
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['${opts.framework === "vue" ? "vue" : "react"}'],
        },
      },
    },
  },
});
`;
}

export function envProductionFile(vars: Record<string, string>): string {
  const lines = Object.entries(vars).map(([k, v]) => `${k}=${v}`);
  lines.push("VITE_NATIVEFORGE_NATIVE=true");
  return `# Generated by NativeForge CPR. Never commit this file.\n${lines.join("\n")}\n`;
}

export function tsconfigFile(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: "react-jsx",
        strict: false,
        baseUrl: ".",
        paths: { "@/*": ["./src/*"] },
      },
      include: ["src"],
    },
    null,
    2,
  ) + "\n";
}

/** Vite entry that bridges a plain-HTML project into the Vite build system. */
export function staticBridgeEntry(pages: string[]): string {
  return `// Generated by NativeForge CPR — bridges plain HTML pages into the Vite build.
const PAGES = ${JSON.stringify(pages, null, 2)};

export function resolvePage(pathname: string): string {
  const clean = pathname.replace(/^[.#/]+/, '') || 'index.html';
  return PAGES.includes(clean) ? clean : PAGES[0];
}

export default PAGES;
`;
}

export function canonicalReadme(meta: { framework: string; buildTool: string }): string {
  return `# Canonical project (NativeForge CPR)

This archive is machine generated. It is the canonical representation of the
uploaded source: framework **${meta.framework}**, build tool **${meta.buildTool}**,
Platform release **${PLATFORM_RELEASE.id}**, Node **${PLATFORM_NODE_VERSION}**, Capacitor **${PLATFORM_RELEASE.capacitorVersion}**.

The build pipeline consumes this archive only. The original upload is preserved
untouched under \`original/source.zip\`.
`;
}
