/**
 * Edge-to-Edge plugin wiring (Capacitor 6+ / Android).
 *
 * Produces every file change required to:
 *   1. Draw the WebView under the status & navigation bars (true native edge-to-edge).
 *   2. Keep status-bar icons readable as the page background changes
 *      (dynamic light/dark icons via Capacitor StatusBar).
 *   3. Expose safe-area-inset-* as CSS variables so the user's layout
 *      can respect notches and the gesture pill.
 *
 * Exposes a single `wireEdgeToEdge(...)` entry that returns a list of
 * patches + npm deps + permissions. The build pipeline applies these to
 * the in-memory ProjectFile tree, identical to other plugin generators.
 *
 * Important: we do NOT install the deprecated @capacitor/edge-to-edge plugin,
 * and we do not depend on any edge-to-edge plugin for the native draw-behind
 * behavior. NativeBridge patches MainActivity.java directly with
 * WindowCompat.setDecorFitsSystemWindows(getWindow(), false) after
 * super.onCreate(savedInstanceState), which is the stable native requirement.
 */

import type { ProjectFile } from "@/stores/projectStore";
import {
  type EdgeToEdgeMode,
  DEFAULT_EDGE_TO_EDGE_MODE,
  getEdgeToEdgeMode,
  EDGE_TO_EDGE_SPACER_TS,
  EDGE_TO_EDGE_COLORS_XML,
  EDGE_TO_EDGE_COLORS_NIGHT_XML,
  TINTED_STYLES_XML,
  TINTED_STYLES_NIGHT_XML,
  SAFE_AREA_VARS_CSS,
  SAFE_AREA_PADDED_CSS,
} from "./modes";

export type { EdgeToEdgeMode };

export interface EdgeToEdgePatch {
  path: string;
  op: "create" | "patch";
  content: string;
  reason: string;
}

export interface EdgeToEdgeWiring {
  npmDeps: string[];
  patches: EdgeToEdgePatch[];
  warnings: string[];
  mode?: EdgeToEdgeMode;
}


const flatten = (files: ProjectFile[]): ProjectFile[] => {
  const out: ProjectFile[] = [];
  const walk = (nodes: ProjectFile[]) => {
    for (const n of nodes) {
      out.push(n);
      if (n.children) walk(n.children);
    }
  };
  walk(files);
  return out;
};

const findEntryFile = (files: ProjectFile[]): ProjectFile | null => {
  const flat = flatten(files);
  const candidates = [
    "src/main.tsx",
    "src/main.ts",
    "src/index.tsx",
    "src/index.ts",
    "src/main.jsx",
    "src/main.js",
  ];
  for (const c of candidates) {
    const hit = flat.find(f => f.type === "file" && (f.path === c || f.path.endsWith(`/${c}`)));
    if (hit) return hit;
  }
  return null;
};

/* ───────────── Runtime modules injected into the user's web app ───────────── */

export const EDGE_TO_EDGE_RUNTIME_TS = `// Auto-generated by NativeBridge — Edge-to-Edge runtime.
// Detects the page background and flips status-bar icons (light/dark) so
// they stay readable. Also enables WebView overlay so the app draws
// behind the status/navigation bars.
import { Capacitor } from "@capacitor/core";
import { StatusBar, Style } from "@capacitor/status-bar";

const RGB_RE = /rgba?\\(([^)]+)\\)/;

function parseColor(c: string): { r: number; g: number; b: number; a: number } | null {
  const m = c.match(RGB_RE);
  if (!m) return null;
  const parts = m[1].split(",").map(v => parseFloat(v.trim()));
  const [r, g, b] = parts;
  const a = parts.length >= 4 ? parts[3] : 1;
  if ([r, g, b].some(n => Number.isNaN(n))) return null;
  return { r, g, b, a: Number.isNaN(a) ? 1 : a };
}

function pickProbeColor(): { r: number; g: number; b: number } | null {
  const htmlAttr = document.documentElement.getAttribute("data-status-bar");
  if (htmlAttr === "light") return { r: 0, g: 0, b: 0 };
  if (htmlAttr === "dark") return { r: 255, g: 255, b: 255 };

  const themeMeta = document.querySelector('meta[name="theme-color"]') as HTMLMetaElement | null;
  if (themeMeta?.content) {
    const probe = document.createElement("span");
    probe.style.color = themeMeta.content;
    document.body.appendChild(probe);
    const parsed = parseColor(getComputedStyle(probe).color);
    probe.remove();
    if (parsed && parsed.a > 0.05) return parsed;
  }

  const x = Math.max(1, Math.floor(window.innerWidth / 2));
  const candidates: (Element | null)[] = [
    document.querySelector("[data-status-bar-probe]"),
    document.elementFromPoint(x, 4),
    document.elementFromPoint(x, 12),
    document.getElementById("root"),
    document.getElementById("__next"),
    document.body,
    document.documentElement,
  ];
  for (const el of candidates) {
    if (!el) continue;
    const parsed = parseColor(getComputedStyle(el).backgroundColor);
    if (parsed && parsed.a > 0.05) return parsed;
  }
  return null;
}

function isDarkBg(): boolean {
  const c = pickProbeColor();
  if (!c) return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
  const toLin = (v: number) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  const L = 0.2126 * toLin(c.r) + 0.7152 * toLin(c.g) + 0.0722 * toLin(c.b);
  return L < 0.5;
}

let lastStyle: Style | null = null;
async function syncStatusBar() {
  if (!Capacitor.isNativePlatform()) return;
  try {
    const next = isDarkBg() ? Style.Light : Style.Dark;
    if (next === lastStyle) return;
    lastStyle = next;
    await StatusBar.setStyle({ style: next });
  } catch (e) {
    console.warn("[edge-to-edge] setStyle failed:", e);
  }
}

function scheduleSync() {
  requestAnimationFrame(() => { void syncStatusBar(); });
}

export async function initEdgeToEdge() {
  if (!Capacitor.isNativePlatform()) return;
  try {
    await StatusBar.setOverlaysWebView({ overlay: true });
    await StatusBar.setBackgroundColor({ color: "#00000000" });
  } catch (e) {
    console.warn("[edge-to-edge] overlay setup failed:", e);
  }
  await syncStatusBar();

  const observer = new MutationObserver(scheduleSync);
  observer.observe(document.body, { attributes: true, attributeFilter: ["class", "style", "data-theme", "data-status-bar"] });
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ["class", "style", "data-theme", "data-status-bar"] });
  if (document.head) new MutationObserver(scheduleSync).observe(document.head, { childList: true, subtree: true, attributes: true });

  window.matchMedia?.("(prefers-color-scheme: dark)").addEventListener?.("change", scheduleSync);
  window.addEventListener("popstate", scheduleSync);

  const wrap = (key: "pushState" | "replaceState") => {
    const orig = history[key];
    history[key] = function (...args: any[]) {
      const ret = orig.apply(this, args as any);
      scheduleSync();
      return ret;
    } as any;
  };
  wrap("pushState"); wrap("replaceState");
}

if (typeof window !== "undefined") {
  if (document.readyState === "complete" || document.readyState === "interactive") {
    void initEdgeToEdge();
  } else {
    window.addEventListener("DOMContentLoaded", () => { void initEdgeToEdge(); });
  }
}
`;

export const SAFE_AREA_CSS = `/* Auto-generated by NativeBridge — safe-area CSS variables. */
:root {
  --sat: env(safe-area-inset-top, 0px);
  --sab: env(safe-area-inset-bottom, 0px);
  --sal: env(safe-area-inset-left, 0px);
  --sar: env(safe-area-inset-right, 0px);
}

:where(html, body) {
  margin: 0;
  background-color: inherit;
}

:where(#root, #__next) {
  padding-top: var(--sat);
  padding-bottom: var(--sab);
  padding-left: var(--sal);
  padding-right: var(--sar);
  box-sizing: border-box;
  min-height: 100dvh;
}

.safe-top    { padding-top: var(--sat); }
.safe-bottom { padding-bottom: var(--sab); }
.safe-x      { padding-left: var(--sal); padding-right: var(--sar); }
.safe-all    { padding: var(--sat) var(--sar) var(--sab) var(--sal); }

.safe-area-fill-top    { margin-top: calc(var(--sat) * -1); padding-top: var(--sat); }
.safe-area-fill-bottom { margin-bottom: calc(var(--sab) * -1); padding-bottom: var(--sab); }
`;

/* ───────────── Native (Android) file generators ───────────── */

const FALLBACK_STYLES_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:statusBarColor">@android:color/transparent</item>
    <item name="android:navigationBarColor">@android:color/transparent</item>
    <item name="android:windowTranslucentStatus">false</item>
    <item name="android:windowTranslucentNavigation">false</item>
    <item name="android:enforceStatusBarContrast" tools:targetApi="29">false</item>
    <item name="android:enforceNavigationBarContrast" tools:targetApi="29">false</item>
    <item name="android:windowLayoutInDisplayCutoutMode" tools:targetApi="27">shortEdges</item>
  </style>
</resources>
`;

const TRUE_EDGE_TO_EDGE_CALL = `WindowCompat.setDecorFitsSystemWindows(getWindow(), false);`;
const MAIN_ACTIVITY_EDGE_TO_EDGE_SNIPPET = `
        // True native edge-to-edge. super.onCreate(...) must run first so Capacitor creates the WebView.
        ${TRUE_EDGE_TO_EDGE_CALL}`;

const MAIN_ACTIVITY_IMPORTS = [
  `import android.os.Bundle;`,
  `import androidx.core.view.WindowCompat;`,
];

function ensureJavaImports(content: string, imports: string[]): string {
  const missing = imports.filter((imp) => !content.includes(imp));
  if (missing.length === 0) return content;
  const block = `\n${missing.join("\n")}\n`;
  const packageMatch = content.match(/(package\s+[^;]+;\s*)/);
  if (packageMatch) return content.replace(packageMatch[1], `${packageMatch[1]}${block}`);
  const firstImport = content.match(/^import\s+[^;]+;\s*/m);
  if (firstImport) return content.replace(firstImport[0], `${block}${firstImport[0]}`);
  return `${missing.join("\n")}\n${content}`;
}

function patchMainActivity(content: string): string {
  let out = ensureJavaImports(content, MAIN_ACTIVITY_IMPORTS);
  out = out.replace(
    /\n\s*\/\/ True native edge-to-edge[\s\S]*?\n\s*WindowCompat\.setDecorFitsSystemWindows\(getWindow\(\),\s*false\);/g,
    "",
  );
  out = out.replace(/\n\s*WindowCompat\.setDecorFitsSystemWindows\(getWindow\(\),\s*false\);/g, "");

  if (/super\.onCreate\(savedInstanceState\);/.test(out)) {
    out = out.replace(/(super\.onCreate\(savedInstanceState\);)/, `$1${MAIN_ACTIVITY_EDGE_TO_EDGE_SNIPPET}`);
  } else if (/onCreate\s*\(\s*Bundle\s+savedInstanceState\s*\)\s*\{/.test(out)) {
    out = out.replace(
      /(onCreate\s*\(\s*Bundle\s+savedInstanceState\s*\)\s*\{)/,
      `$1\n        super.onCreate(savedInstanceState);${MAIN_ACTIVITY_EDGE_TO_EDGE_SNIPPET}`,
    );
  } else {
    out = out.replace(
      /\n}\s*$/,
      `\n\n    @Override\n    protected void onCreate(Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);${MAIN_ACTIVITY_EDGE_TO_EDGE_SNIPPET}\n    }\n}\n`,
    );
  }
  return out;
}

function patchStylesXml(content: string): string {
  let out = content.includes("xmlns:tools=")
    ? content
    : content.replace(/<resources([^>]*)>/, `<resources$1 xmlns:tools="http://schemas.android.com/tools">`);
  const edgeItems = [
    `<item name="android:statusBarColor">@android:color/transparent</item>`,
    `<item name="android:navigationBarColor">@android:color/transparent</item>`,
    `<item name="android:windowTranslucentStatus">false</item>`,
    `<item name="android:windowTranslucentNavigation">false</item>`,
    `<item name="android:enforceStatusBarContrast" tools:targetApi="29">false</item>`,
    `<item name="android:enforceNavigationBarContrast" tools:targetApi="29">false</item>`,
    `<item name="android:windowLayoutInDisplayCutoutMode" tools:targetApi="27">shortEdges</item>`,
  ];
  for (const item of [
    "android:statusBarColor",
    "android:navigationBarColor",
    "android:windowTranslucentStatus",
    "android:windowTranslucentNavigation",
    "android:enforceStatusBarContrast",
    "android:enforceNavigationBarContrast",
    "android:windowLayoutInDisplayCutoutMode",
  ]) {
    out = out.replace(new RegExp(`\\s*<item name=["']${item}["'][\\s\\S]*?<\\/item>`, "g"), "");
  }
  const block = edgeItems.map((item) => `\n        ${item}`).join("");
  let inserted = false;
  for (const styleName of ["AppTheme", "AppTheme.NoActionBar"]) {
    const styleRe = new RegExp(`(<style\\s+name=["']${styleName.replace(/\./g, "\\.")}["'][^>]*>)`);
    if (styleRe.test(out)) {
      out = out.replace(styleRe, `$1${block}`);
      inserted = true;
    }
  }
  if (inserted) {
    return out;
  }
  return out.replace(/<\/resources>/, `\n    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">${block}\n    </style>\n</resources>`);
}

function patchAppBuildGradle(content: string): string {
  if (content.includes("androidx.core:core")) return content;
  const dep = content.includes("$androidxCoreVersion")
    ? `    implementation "androidx.core:core:$androidxCoreVersion"`
    : `    implementation "androidx.core:core:1.15.0"`;
  if (/dependencies\s*\{[\s\S]*?\n\}/.test(content)) {
    return content.replace(/(dependencies\s*\{)/, `$1\n${dep}`);
  }
  return `${content.trimEnd()}\n\ndependencies {\n${dep}\n}\n`;
}

function patchEntryFile(content: string, relativeImport: string): string {
  if (content.includes(relativeImport)) return content;
  // Insert after the last import line at top
  const lines = content.split("\n");
  let lastImport = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^\s*import\s/.test(lines[i])) lastImport = i;
    else if (lastImport >= 0 && lines[i].trim() !== "") break;
  }
  const insertAt = lastImport + 1;
  lines.splice(insertAt, 0, `import "${relativeImport}";`);
  return lines.join("\n");
}

function patchIndexHtml(content: string): string {
  let out = content;
  if (!/viewport-fit\s*=\s*cover/.test(out)) {
    out = out.replace(
      /<meta\s+name=["']viewport["']\s+content=["']([^"']+)["']\s*\/?\s*>/,
      (_m, attr) => {
        const next = /viewport-fit/.test(attr) ? attr : `${attr.replace(/\s*$/, "")}, viewport-fit=cover`;
        return `<meta name="viewport" content="${next}" />`;
      },
    );
  }
  if (!/<meta\s+name=["']theme-color["']/i.test(out)) {
    out = out.replace(/<\/head>/i, `  <meta name="theme-color" content="#ffffff" />\n</head>`);
  }
  return out;
}

/* ───────────── Entry point ───────────── */

/**
 * The runtime module adapts to the selected mode: overlay + transparent bars
 * for the draw-behind modes, opaque tint sync for `status-bar-tint`.
 */
export function edgeToEdgeRuntime(mode: EdgeToEdgeMode): string {
  if (mode !== "status-bar-tint") return EDGE_TO_EDGE_RUNTIME_TS;
  return EDGE_TO_EDGE_RUNTIME_TS.replace(
    `    await StatusBar.setOverlaysWebView({ overlay: true });\n    await StatusBar.setBackgroundColor({ color: "#00000000" });`,
    `    await StatusBar.setOverlaysWebView({ overlay: false });\n    const probe = pickProbeColor();\n    if (probe) {\n      const hex = "#" + [probe.r, probe.g, probe.b].map(v => Math.round(v).toString(16).padStart(2, "0")).join("");\n      await StatusBar.setBackgroundColor({ color: hex });\n    }`,
  );
}

export function wireEdgeToEdge(
  files: ProjectFile[],
  mode: EdgeToEdgeMode = DEFAULT_EDGE_TO_EDGE_MODE,
): EdgeToEdgeWiring {
  const spec = getEdgeToEdgeMode(mode);
  const wiring: EdgeToEdgeWiring = {
    npmDeps: [
      "@capacitor/status-bar",
      "@capacitor/app",
    ],
    patches: [],
    warnings: [],
    mode: spec.id,
  };

  const flat = flatten(files);

  // 1. Runtime module
  wiring.patches.push({
    path: "src/capacitor/edgeToEdge.ts",
    op: "create",
    content: edgeToEdgeRuntime(spec.id),
    reason: `Edge-to-edge runtime (${spec.label}) + dynamic status-bar style`,
  });

  // 1b. Spacer runtime — only for websites that were never built for edge-to-edge.
  if (spec.injectsSpacer) {
    wiring.patches.push({
      path: "src/capacitor/edgeToEdgeSpacer.ts",
      op: "create",
      content: EDGE_TO_EDGE_SPACER_TS,
      reason: "Status-bar-height spacer with fade, painted from the app background",
    });
  }


  // 2. Safe-area CSS — the spacer mode offsets the app, the other modes only
  //    publish the variables so existing layouts keep control.
  wiring.patches.push({
    path: "src/capacitor/safe-area.css",
    op: "create",
    content: spec.injectsSpacer ? SAFE_AREA_PADDED_CSS : spec.drawsBehindBars ? SAFE_AREA_CSS : SAFE_AREA_VARS_CSS,
    reason: `Safe-area CSS for "${spec.label}"`,
  });

  // 3. Inject import into entry file
  const entry = findEntryFile(files);
  if (entry?.content) {
    let next = patchEntryFile(entry.content, "./capacitor/edgeToEdge");
    if (spec.injectsSpacer) next = patchEntryFile(next, "./capacitor/edgeToEdgeSpacer");
    next = patchEntryFile(next, "./capacitor/safe-area.css");
    if (next !== entry.content) {
      wiring.patches.push({
        path: entry.path,
        op: "patch",
        content: next,
        reason: "Import edge-to-edge runtime + safe-area styles",
      });
    }
  } else {
    wiring.warnings.push("Could not find a web entry file (src/main.tsx etc.) — runtime auto-init may not fire.");
  }

  // 4. Patch index.html viewport (only needed when drawing behind the bars)
  const indexHtml = flat.find(f => f.type === "file" && (f.path === "index.html" || f.path.endsWith("/index.html")));
  if (spec.drawsBehindBars && indexHtml?.content) {
    const next = patchIndexHtml(indexHtml.content);
    if (next !== indexHtml.content) {
      wiring.patches.push({
        path: indexHtml.path,
        op: "patch",
        content: next,
        reason: "Add viewport-fit=cover so CSS env(safe-area-inset-*) resolves",
      });
    }
  }

  // 5. Android resources.
  const stylesPath = "android/app/src/main/res/values/styles.xml";
  const stylesExisting = flat.find(f => f.path === stylesPath);

  if (spec.tintsStatusBar) {
    // Capacitor never generates the night-qualified resource folders, so the
    // status bar cannot follow dark mode. NativeBridge creates them.
    const light = "#FFFFFF";
    const dark = "#0B0B0F";
    wiring.patches.push({
      path: "android/app/src/main/res/values/colors.xml",
      op: flat.some(f => f.path === "android/app/src/main/res/values/colors.xml") ? "patch" : "create",
      content: EDGE_TO_EDGE_COLORS_XML(light, dark),
      reason: "System bar colours (light theme)",
    });
    wiring.patches.push({
      path: "android/app/src/main/res/values-night/colors.xml",
      op: "create",
      content: EDGE_TO_EDGE_COLORS_NIGHT_XML(dark),
      reason: "System bar colours (dark theme)",
    });
    wiring.patches.push({
      path: stylesPath,
      op: stylesExisting ? "patch" : "create",
      content: TINTED_STYLES_XML(false),
      reason: "Opaque status/navigation bars tinted to the app background",
    });
    wiring.patches.push({
      path: "android/app/src/main/res/values-night/styles.xml",
      op: "create",
      content: TINTED_STYLES_NIGHT_XML,
      reason: "Dark-mode variant so the bars flip with the system theme",
    });
  } else {
    const stylesNext = stylesExisting?.content ? patchStylesXml(stylesExisting.content) : FALLBACK_STYLES_XML;
    if (!stylesExisting || stylesExisting.content !== stylesNext) {
      wiring.patches.push({
        path: stylesPath,
        op: stylesExisting ? "patch" : "create",
        content: stylesNext,
        reason: "Transparent system bars + true edge-to-edge AppTheme attributes",
      });
    }
    wiring.patches.push({
      path: "android/app/src/main/res/values-night/styles.xml",
      op: "create",
      content: stylesNext.replace("<!-- Auto-generated", "<!-- Dark-mode variant. Auto-generated"),
      reason: "Dark-mode variant of the edge-to-edge theme",
    });
  }


  // 6. app/build.gradle — WindowCompat comes from AndroidX Core
  const appGradlePath = "android/app/build.gradle";
  const appGradle = flat.find(f => f.path === appGradlePath);
  if (appGradle?.content) {
    const next = patchAppBuildGradle(appGradle.content);
    if (next !== appGradle.content) {
      wiring.patches.push({
        path: appGradle.path,
        op: "patch",
        content: next,
        reason: "Add AndroidX Core for WindowCompat true edge-to-edge",
      });
    }
  }

  // 7. MainActivity.java — inject WindowCompat call immediately after super.onCreate(...)
  //    Only the draw-behind modes touch the native window; the tinted mode must
  //    keep the default inset behaviour so the bars stay opaque.
  const mainActivity = flat.find(
    f => f.type === "file" && f.path.endsWith("MainActivity.java"),
  );
  if (spec.drawsBehindBars) {
    if (mainActivity?.content) {
      const next = patchMainActivity(mainActivity.content);
      if (next !== mainActivity.content) {
        wiring.patches.push({
          path: mainActivity.path,
          op: "patch",
          content: next,
          reason: "Enable true edge-to-edge directly in MainActivity after Capacitor setup",
        });
      }
    } else {
      // Will be created by Phase 1 — re-run will pick it up.
      wiring.warnings.push("MainActivity.java not present yet (Phase 1 will generate it). NativeBridge will re-run true edge-to-edge wiring after Phase 1.");
    }
  }


  return wiring;
}

export function wiringToLogs(w: EdgeToEdgeWiring): string[] {
  const logs: string[] = [];
  logs.push(`Edge-to-Edge: ${w.patches.length} file change${w.patches.length === 1 ? "" : "s"}`);
  for (const p of w.patches) logs.push(`  ${p.op === "create" ? "+" : "~"} ${p.path}  — ${p.reason}`);
  for (const dep of w.npmDeps) logs.push(`  npm: ${dep}`);
  for (const wn of w.warnings) logs.push(`  ⚠ ${wn}`);
  return logs;
}
