/**
 * Edge-to-Edge has three distinct usages. The user picks one in the Plugins
 * panel; the choice is persisted as the `EDGE_TO_EDGE_MODE` plugin secret and
 * drives BOTH the deterministic wiring (this module + ./index.ts) and the AI
 * wiring prompt, so the Action Panel only reports what the user actually chose.
 */

export type EdgeToEdgeMode = "spacer-fade" | "status-bar-tint" | "native-ready";

export const DEFAULT_EDGE_TO_EDGE_MODE: EdgeToEdgeMode = "spacer-fade";

export interface EdgeToEdgeModeSpec {
  id: EdgeToEdgeMode;
  label: string;
  tagline: string;
  description: string;
  bestFor: string;
  /** Draw the WebView behind the system bars (WindowCompat decorFitsSystemWindows=false). */
  drawsBehindBars: boolean;
  /** Inject the translucent top spacer with a fade. */
  injectsSpacer: boolean;
  /** Tint the native status bar to the app background instead of overlaying. */
  tintsStatusBar: boolean;
}

export const EDGE_TO_EDGE_MODES: EdgeToEdgeModeSpec[] = [
  {
    id: "spacer-fade",
    label: "Safe spacer + fade",
    tagline: "For websites never designed for edge-to-edge",
    description:
      "Draws behind the system bars, then adds a top spacer exactly the height of the status bar. The spacer is painted with the app's own background colour (re-read at runtime, so it follows light/dark mode) and fades out into the content below — the modern look. Content is pushed down so nothing hides under the status bar. The gesture/navigation area gets a matching bottom inset only when the device reports one, so swipe-navigation phones stay full-bleed.",
    bestFor: "Converted websites, dashboards, any UI with a fixed top bar.",
    drawsBehindBars: true,
    injectsSpacer: true,
    tintsStatusBar: false,
  },
  {
    id: "status-bar-tint",
    label: "Tinted status bar",
    tagline: "Keep the bars, match their colour",
    description:
      "Leaves the system bars in place (no draw-behind) and instead paints the status bar and navigation bar with your app's background colour. NativeBridge generates values/colors.xml and values-night/colors.xml plus the matching styles so the bars flip automatically when the device switches to dark mode.",
    bestFor: "Apps that want a classic, opaque chrome that still matches the theme.",
    drawsBehindBars: false,
    injectsSpacer: false,
    tintsStatusBar: true,
  },
  {
    id: "native-ready",
    label: "Already edge-to-edge",
    tagline: "The app handles its own insets",
    description:
      "For layouts already built for edge-to-edge. NativeBridge only does the native minimum: transparent bars, draw-behind, viewport-fit=cover and the safe-area CSS variables. No spacer and no padding is injected, so your existing insets keep working untouched.",
    bestFor: "Apps already using env(safe-area-inset-*) or a native design system.",
    drawsBehindBars: true,
    injectsSpacer: false,
    tintsStatusBar: false,
  },
];

export function getEdgeToEdgeMode(mode?: string | null): EdgeToEdgeModeSpec {
  return (
    EDGE_TO_EDGE_MODES.find((m) => m.id === mode) ??
    EDGE_TO_EDGE_MODES.find((m) => m.id === DEFAULT_EDGE_TO_EDGE_MODE)!
  );
}

/** Android colour resources used by the tinted mode. */
export const EDGE_TO_EDGE_COLORS_XML = (light: string, dark: string) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by NativeBridge — Edge-to-Edge system bar colours. -->
<resources>
  <color name="nb_status_bar">${light}</color>
  <color name="nb_navigation_bar">${light}</color>
  <color name="nb_status_bar_dark">${dark}</color>
</resources>
`;

export const EDGE_TO_EDGE_COLORS_NIGHT_XML = (dark: string) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by NativeBridge — dark-mode system bar colours. -->
<resources>
  <color name="nb_status_bar">${dark}</color>
  <color name="nb_navigation_bar">${dark}</color>
  <color name="nb_status_bar_dark">${dark}</color>
</resources>
`;

export const TINTED_STYLES_XML = (lightIcons: boolean) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by NativeBridge — tinted system bars. -->
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:statusBarColor">@color/nb_status_bar</item>
    <item name="android:navigationBarColor">@color/nb_navigation_bar</item>
    <item name="android:windowLightStatusBar" tools:targetApi="23">${lightIcons ? "false" : "true"}</item>
    <item name="android:windowTranslucentStatus">false</item>
    <item name="android:windowTranslucentNavigation">false</item>
  </style>
</resources>
`;

export const TINTED_STYLES_NIGHT_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by NativeBridge — tinted system bars (dark mode). -->
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:statusBarColor">@color/nb_status_bar</item>
    <item name="android:navigationBarColor">@color/nb_navigation_bar</item>
    <item name="android:windowLightStatusBar" tools:targetApi="23">false</item>
    <item name="android:windowTranslucentStatus">false</item>
    <item name="android:windowTranslucentNavigation">false</item>
  </style>
</resources>
`;

/**
 * Runtime spacer module. Reads the real page background (body / #root / theme
 * meta) every time the theme changes and paints a status-bar-height spacer
 * with a fade, then offsets the app so no content sits under the status bar.
 */
export const EDGE_TO_EDGE_SPACER_TS = `// Auto-generated by NativeBridge — Edge-to-Edge safe spacer.
// Adds a status-bar-height spacer painted with the app's own background
// colour and faded into the content below. Colour is re-read whenever the
// theme changes so light/dark mode both look correct.
import { Capacitor } from "@capacitor/core";

const SPACER_ID = "nb-status-bar-spacer";
const STYLE_ID = "nb-status-bar-spacer-style";

function readAppBackground(): string {
  const probe: (Element | null)[] = [
    document.querySelector("[data-status-bar-probe]"),
    document.getElementById("root"),
    document.getElementById("__next"),
    document.body,
    document.documentElement,
  ];
  for (const el of probe) {
    if (!el) continue;
    const bg = getComputedStyle(el).backgroundColor;
    if (bg && bg !== "transparent" && !/rgba\\(0,\\s*0,\\s*0,\\s*0\\)/.test(bg)) return bg;
  }
  return window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "#0b0b0f" : "#ffffff";
}

function ensureStyle() {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement("style");
  style.id = STYLE_ID;
  style.textContent = [
    "#" + SPACER_ID + "{position:fixed;top:0;left:0;right:0;z-index:2147483646;",
    "height:calc(env(safe-area-inset-top, 0px) + 2px);pointer-events:none;",
    "-webkit-backdrop-filter:saturate(180%) blur(12px);backdrop-filter:saturate(180%) blur(12px);",
    "transition:background 200ms ease;}",
    ":where(html){--nb-status-bar-height:env(safe-area-inset-top, 0px);}",
    ":where(body){padding-top:var(--nb-status-bar-height);}",
    "@supports (padding: max(0px)) { :where(body){padding-bottom:env(safe-area-inset-bottom, 0px);} }",
  ].join("");
  document.head.appendChild(style);
}

function paint() {
  const bg = readAppBackground();
  const el = document.getElementById(SPACER_ID);
  if (!el) return;
  // Solid at the very top (under the clock/battery), fading into the content.
  el.style.background =
    "linear-gradient(to bottom, " + bg + " 0%, " + bg + " 62%, transparent 100%)";
}

export function initStatusBarSpacer() {
  if (!Capacitor.isNativePlatform()) return;
  ensureStyle();
  if (!document.getElementById(SPACER_ID)) {
    const el = document.createElement("div");
    el.id = SPACER_ID;
    el.setAttribute("aria-hidden", "true");
    document.body.appendChild(el);
  }
  paint();

  const schedule = () => requestAnimationFrame(paint);
  const observer = new MutationObserver(schedule);
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ["class", "style", "data-theme"] });
  observer.observe(document.body, { attributes: true, attributeFilter: ["class", "style", "data-theme"] });
  window.matchMedia?.("(prefers-color-scheme: dark)").addEventListener?.("change", schedule);
  window.addEventListener("popstate", schedule);
}

if (typeof window !== "undefined") {
  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", () => initStatusBarSpacer());
  } else {
    initStatusBarSpacer();
  }
}
`;

/** Safe-area CSS variants per mode. */
export const SAFE_AREA_VARS_CSS = `/* Auto-generated by NativeBridge — safe-area CSS variables. */
:root {
  --sat: env(safe-area-inset-top, 0px);
  --sab: env(safe-area-inset-bottom, 0px);
  --sal: env(safe-area-inset-left, 0px);
  --sar: env(safe-area-inset-right, 0px);
}

:where(html, body) { margin: 0; }

.safe-top    { padding-top: var(--sat); }
.safe-bottom { padding-bottom: var(--sab); }
.safe-x      { padding-left: var(--sal); padding-right: var(--sar); }
.safe-all    { padding: var(--sat) var(--sar) var(--sab) var(--sal); }
`;

export const SAFE_AREA_PADDED_CSS = `${SAFE_AREA_VARS_CSS}
/* Spacer mode: the app root is offset so nothing hides under the status bar. */
:where(#root, #__next) {
  padding-left: var(--sal);
  padding-right: var(--sar);
  box-sizing: border-box;
  min-height: 100dvh;
}
`;
