// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noiioxcxpvfzsqdayjfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaWlveGN4cHZmenNxZGF5amZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0Mzg5OTQsImV4cCI6MjA4NjAxNDk5NH0.uTEHnTzRWtJG7ngWT9-K8cbuOPAiqyKiRyHnTu_LdW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});