/**
 * Display Mode — hook detection & location determination.
 *
 * Implements the "detection before creation" contract:
 *   1. Look for an existing file that already handles status bar / display mode.
 *   2. If one exists it is EXTENDED (never rewritten).
 *   3. If none exists, decide where the new hook file belongs based on the
 *      project structure (hooks → composables → utils → create hooks).
 */

import type { ProjectFile } from "@/stores/projectStore";

export interface HookDetection {
  /** Path of the file that will own (or already owns) the display-mode logic. */
  hookPath: string;
  /** True when an existing handler was found and will be extended. */
  hookExisted: boolean;
  /** Why this file was chosen — surfaced in the pre-flight report. */
  reason: string;
  /** Conflicting status-bar logic we found but must not overwrite. */
  conflicts: string[];
  language: "ts" | "js";
  framework: "react" | "vue" | "svelte" | "plain";
}

export const flattenFiles = (files: ProjectFile[]): ProjectFile[] => {
  const out: ProjectFile[] = [];
  const walk = (nodes: ProjectFile[]) => {
    for (const n of nodes) {
      out.push(n);
      if (n.children) walk(n.children);
    }
  };
  walk(files);
  return out;
};

const NAME_PATTERNS = [
  "usestatusbar",
  "usedisplaymode",
  "usesystemui",
  "usenativeui",
  "useappearance",
  "usetheme",
  "statusbar",
  "displaymode",
  "systemui",
];

const isSource = (p: string) => /\.(t|j)sx?$|\.vue$|\.svelte$/.test(p);
const inSrc = (p: string) => p === "src" || p.startsWith("src/") || p.includes("/src/");

function detectFramework(flat: ProjectFile[]): HookDetection["framework"] {
  const pkg = flat.find((f) => f.path === "package.json" || f.path.endsWith("/package.json"));
  const deps = (() => {
    try {
      const j = JSON.parse(pkg?.content || "{}");
      return { ...(j.dependencies || {}), ...(j.devDependencies || {}) } as Record<string, string>;
    } catch {
      return {} as Record<string, string>;
    }
  })();
  if (deps.react || flat.some((f) => f.path.endsWith(".tsx") || f.path.endsWith(".jsx"))) return "react";
  if (deps.vue || flat.some((f) => f.path.endsWith(".vue"))) return "vue";
  if (deps.svelte || flat.some((f) => f.path.endsWith(".svelte"))) return "svelte";
  return "plain";
}

function detectLanguage(flat: ProjectFile[]): "ts" | "js" {
  return flat.some((f) => /(^|\/)tsconfig(\.\w+)?\.json$/.test(f.path) || /\.tsx?$/.test(f.path))
    ? "ts"
    : "js";
}

export function detectDisplayModeHook(files: ProjectFile[]): HookDetection {
  const flat = flattenFiles(files);
  const framework = detectFramework(flat);
  const language = detectLanguage(flat);
  const conflicts: string[] = [];

  const sources = flat.filter((f) => f.type === "file" && inSrc(f.path) && isSource(f.path));

  // Scan 1 — file name patterns.
  const byName = sources.find((f) => {
    const base = f.path.split("/").pop()!.toLowerCase();
    // Ignore files we generated ourselves.
    if (base.startsWith("display-mode")) return false;
    return NAME_PATTERNS.some((p) => base.includes(p));
  });

  // Scan 2 — imports of StatusBar from @capacitor/status-bar.
  const byImport = sources.find(
    (f) => f.content && /@capacitor\/status-bar/.test(f.content) && !/Auto-generated by NativeForge/.test(f.content),
  );

  // Scan 3 — direct StatusBar API calls.
  const byCall = sources.find(
    (f) =>
      f.content &&
      /StatusBar\.(setStyle|setBackgroundColor|setOverlaysWebView)/.test(f.content) &&
      !/Auto-generated by NativeForge/.test(f.content),
  );

  for (const hit of [byImport, byCall]) {
    if (hit && !conflicts.includes(hit.path)) conflicts.push(hit.path);
  }

  const existing = byName || byImport || byCall;
  if (existing) {
    return {
      hookPath: existing.path,
      hookExisted: true,
      reason: `Existing display-mode handler found at ${existing.path} — extending it instead of creating a new file`,
      conflicts,
      language,
      framework,
    };
  }

  // Location determination.
  const ext = language === "ts" ? "ts" : "js";
  const hasDir = (dir: string) => flat.some((f) => f.path === dir || f.path.startsWith(`${dir}/`));

  if (framework === "plain") {
    return {
      hookPath: "src/scripts/displayMode.js",
      hookExisted: false,
      reason: "Plain HTML project — display mode script created at src/scripts/displayMode.js",
      conflicts,
      language,
      framework,
    };
  }
  if (hasDir("src/hooks")) {
    return { hookPath: `src/hooks/useDisplayMode.${ext}`, hookExisted: false, reason: "src/hooks exists — hook created there", conflicts, language, framework };
  }
  if (framework === "vue" && hasDir("src/composables")) {
    return { hookPath: `src/composables/useDisplayMode.${ext}`, hookExisted: false, reason: "src/composables exists — composable created there", conflicts, language, framework };
  }
  if (hasDir("src/composables")) {
    return { hookPath: `src/composables/useDisplayMode.${ext}`, hookExisted: false, reason: "src/composables exists — hook created there", conflicts, language, framework };
  }
  if (hasDir("src/utils")) {
    return { hookPath: `src/utils/useDisplayMode.${ext}`, hookExisted: false, reason: "src/utils exists — hook created there", conflicts, language, framework };
  }
  return {
    hookPath: `src/hooks/useDisplayMode.${ext}`,
    hookExisted: false,
    reason: "No hooks/composables/utils folder — src/hooks created",
    conflicts,
    language,
    framework,
  };
}

/** Relative import specifier from `fromPath` to `toPath` (no extension). */
export function relativeImport(fromPath: string, toPath: string): string {
  const from = fromPath.split("/").slice(0, -1);
  const to = toPath.replace(/\.(tsx?|jsx?)$/, "").split("/");
  let i = 0;
  while (i < from.length && i < to.length && from[i] === to[i]) i++;
  const up = from.length - i;
  const rel = [...(up === 0 ? ["."] : Array(up).fill("..")), ...to.slice(i)].join("/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}
