/**
 * File templates emitted by the Display Mode plugin.
 *
 * Every template is deterministic: the same config always produces the same
 * bytes, so re-running the wiring step is idempotent.
 */

import type { DisplayModeConfig, DisplayModeSpec } from "./registry";

const TRANSPARENT = "#00000000";

const header = (what: string) =>
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Auto-generated by NativeForge Display Mode — ${what}. Do not edit by hand. -->`;

interface ThemeVars {
  statusBarColor: string;
  navigationBarColor: string;
  lightStatusIcons: boolean; // windowLightStatusBar (true = dark icons)
  lightNavIcons: boolean;
  edgeToEdge: boolean;
  fitsSystemWindows: boolean;
  v31: boolean;
}

function stylesXml(v: ThemeVars, note: string): string {
  const items: string[] = [
    `<item name="android:windowLightStatusBar" tools:targetApi="23">${v.lightStatusIcons}</item>`,
    `<item name="android:windowLightNavigationBar" tools:targetApi="27">${v.lightNavIcons}</item>`,
    `<item name="android:fitsSystemWindows">${v.fitsSystemWindows}</item>`,
    `<item name="android:windowLayoutInDisplayCutoutMode" tools:targetApi="27">shortEdges</item>`,
  ];

  if (v.edgeToEdge) {
    items.unshift(
      `<item name="android:statusBarColor">${TRANSPARENT}</item>`,
      `<item name="android:navigationBarColor">${TRANSPARENT}</item>`,
      `<item name="android:windowDrawsSystemBarBackgrounds">true</item>`,
    );
    if (v.v31) {
      // Android 12+ uses the WindowInsetsController contrast enforcement.
      items.push(
        `<item name="android:enforceStatusBarContrast" tools:targetApi="29">false</item>`,
        `<item name="android:enforceNavigationBarContrast" tools:targetApi="29">false</item>`,
      );
    } else {
      // Pre-Android-12 attributes only. Never mix them with the v31 set.
      items.push(
        `<item name="android:windowTranslucentStatus">true</item>`,
        `<item name="android:windowTranslucentNavigation">true</item>`,
      );
    }
  } else {
    items.unshift(
      `<item name="android:statusBarColor">${v.statusBarColor}</item>`,
      `<item name="android:navigationBarColor">${v.navigationBarColor}</item>`,
      `<item name="android:windowDrawsSystemBarBackgrounds">true</item>`,
    );
    items.push(
      `<item name="android:windowTranslucentStatus">false</item>`,
      `<item name="android:windowTranslucentNavigation">false</item>`,
    );
    if (v.v31) {
      items.push(
        `<item name="android:enforceStatusBarContrast" tools:targetApi="29">false</item>`,
        `<item name="android:enforceNavigationBarContrast" tools:targetApi="29">false</item>`,
      );
    }
  }

  const body = items.map((i) => `        ${i}`).join("\n");
  return `${header(note)}
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
${body}
    </style>
    <style name="AppTheme.NoActionBar" parent="AppTheme">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@drawable/splash</item>
    </style>
</resources>
`;
}

/** All four resource folders for the selected mode. */
export function androidStyleFiles(
  spec: DisplayModeSpec,
  cfg: DisplayModeConfig,
): { path: string; content: string; reason: string }[] {
  const edge = spec.overlaysWebView;
  const lightIconsLight = cfg.lightModeIconStyle === "DARK"; // DARK icons => windowLightStatusBar true

  const light = (v31: boolean) =>
    stylesXml(
      {
        statusBarColor: cfg.lightStatusBarColor,
        navigationBarColor: cfg.lightNavigationBarColor,
        lightStatusIcons: lightIconsLight,
        lightNavIcons: lightIconsLight,
        edgeToEdge: edge,
        fitsSystemWindows: spec.fitsSystemWindows,
        v31,
      },
      v31 ? "Android 12+ light theme" : "light theme",
    );

  const dark = (v31: boolean) =>
    stylesXml(
      {
        statusBarColor: cfg.darkStatusBarColor,
        navigationBarColor: cfg.darkNavigationBarColor,
        lightStatusIcons: false, // dark mode is always LIGHT icons
        lightNavIcons: false,
        edgeToEdge: edge,
        fitsSystemWindows: spec.fitsSystemWindows,
        v31,
      },
      v31 ? "Android 12+ dark theme" : "dark theme",
    );

  return [
    { path: "android/app/src/main/res/values/styles.xml", content: light(false), reason: "System bars — Android 11 and below, light theme" },
    { path: "android/app/src/main/res/values-night/styles.xml", content: dark(false), reason: "System bars — Android 11 and below, dark theme" },
    { path: "android/app/src/main/res/values-v31/styles.xml", content: light(true), reason: "System bars — Android 12+, light theme" },
    { path: "android/app/src/main/res/values-night-v31/styles.xml", content: dark(true), reason: "System bars — Android 12+, dark theme" },
  ];
}

export function androidColorFiles(
  cfg: DisplayModeConfig,
): { path: string; content: string; reason: string }[] {
  const colors = (status: string, nav: string, note: string) => `${header(note)}
<resources>
    <color name="nf_status_bar">${status}</color>
    <color name="nf_navigation_bar">${nav}</color>
</resources>
`;
  return [
    { path: "android/app/src/main/res/values/colors.xml", content: colors(cfg.lightStatusBarColor, cfg.lightNavigationBarColor, "light system bar colours"), reason: "System bar colours (light)" },
    { path: "android/app/src/main/res/values-night/colors.xml", content: colors(cfg.darkStatusBarColor, cfg.darkNavigationBarColor, "dark system bar colours"), reason: "System bar colours (dark)" },
  ];
}

/* ───────────────────────── Web assets ───────────────────────── */

export const SAFE_AREA_VARS_CSS = `/* Auto-generated by NativeForge Display Mode — safe-area variables. */
:root {
  --nf-sat: env(safe-area-inset-top, 0px);
  --nf-sab: env(safe-area-inset-bottom, 0px);
  --nf-sal: env(safe-area-inset-left, 0px);
  --nf-sar: env(safe-area-inset-right, 0px);
}

:where(html, body) { margin: 0; }

.safe-top    { padding-top: var(--nf-sat); }
.safe-bottom { padding-bottom: var(--nf-sab); }
.safe-x      { padding-left: var(--nf-sal); padding-right: var(--nf-sar); }
.safe-all    { padding: var(--nf-sat) var(--nf-sar) var(--nf-sab) var(--nf-sal); }
`;

/** Mode 3/4/5: push app content away from the system UI. */
export const SAFE_AREA_PADDING_CSS = `${SAFE_AREA_VARS_CSS}
/* Body padding so no content hides under the status or navigation bar. */
body {
  padding-top: var(--nf-sat);
  padding-bottom: var(--nf-sab);
  padding-left: var(--nf-sal);
  padding-right: var(--nf-sar);
  box-sizing: border-box;
}

/* Fixed bottom chrome (tab bars, bottom nav) must clear the gesture area. */
body [data-nf-bottom-bar],
body .bottom-nav,
body .tab-bar,
body nav[class*="bottom"] {
  padding-bottom: calc(var(--nf-sab) + var(--nf-bottom-bar-extra, 0px));
}

/* Full-screen pages (mode 5) opt out of body padding entirely. */
body[data-nf-fullscreen="true"] {
  padding-top: 0;
  padding-bottom: 0;
}
body[data-nf-fullscreen="true"] [data-nf-safe-top] {
  padding-top: var(--nf-sat);
}
body[data-nf-fullscreen="true"] [data-nf-safe-bottom] {
  padding-bottom: var(--nf-sab);
}
`;

export const GLASS_CSS = `/* Auto-generated by NativeForge Display Mode — glassmorphism layers. */
#nf-glass-top,
#nf-glass-bottom {
  position: fixed;
  left: 0;
  right: 0;
  z-index: 2147483646;
  pointer-events: none;
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  backdrop-filter: blur(20px) saturate(180%);
  background-color: rgba(255, 255, 255, 0.7);
  transition: background-color 300ms ease;
}
#nf-glass-top    { top: 0;    height: env(safe-area-inset-top, 0px); }
#nf-glass-bottom { bottom: 0; height: env(safe-area-inset-bottom, 0px); }

html[data-nf-scheme="dark"] #nf-glass-top,
html[data-nf-scheme="dark"] #nf-glass-bottom {
  background-color: rgba(0, 0, 0, 0.7);
}
`;

/**
 * Mode 2/3/4/5 — reads the real body background, computes relative luminance
 * and drives the native bars. Re-runs on DOM mutation, system theme change and
 * app resume.
 */
export function colorMatchingModule(cfg: DisplayModeConfig, spec: DisplayModeSpec): string {
  return `// Auto-generated by NativeForge Display Mode — runtime colour matching.
import { Capacitor } from "@capacitor/core";
import { StatusBar, Style } from "@capacitor/status-bar";
import { App } from "@capacitor/app";

const OVERLAYS = ${spec.overlaysWebView};
const LIGHT_FALLBACK = "${cfg.lightStatusBarColor}";
const DARK_FALLBACK = "${cfg.darkStatusBarColor}";

function toHex(rgb: string, fallback: string): { hex: string; luminance: number } {
  const m = rgb.match(/rgba?\\(([^)]+)\\)/);
  let r: number, g: number, b: number, a = 1;
  if (m) {
    const parts = m[1].split(",").map((v) => parseFloat(v.trim()));
    [r, g, b] = parts;
    if (parts.length >= 4) a = parts[3];
  } else {
    const f = fallback.replace("#", "");
    r = parseInt(f.slice(0, 2), 16);
    g = parseInt(f.slice(2, 4), 16);
    b = parseInt(f.slice(4, 6), 16);
  }
  if ([r, g, b].some((n) => Number.isNaN(n)) || a < 0.05) {
    return toHex("", fallback);
  }
  const lin = (v: number) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  const luminance = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
  const hx = (n: number) => Math.round(n).toString(16).padStart(2, "0");
  return { hex: "#" + hx(r) + hx(g) + hx(b), luminance };
}

function readBackground(): { hex: string; luminance: number } {
  const prefersDark = window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
  const fallback = prefersDark ? DARK_FALLBACK : LIGHT_FALLBACK;
  const probes: (Element | null)[] = [
    document.querySelector("[data-nf-color-probe]"),
    document.body,
    document.getElementById("root"),
    document.getElementById("__next"),
    document.documentElement,
  ];
  for (const el of probes) {
    if (!el) continue;
    const bg = window.getComputedStyle(el).backgroundColor;
    if (bg && bg !== "transparent" && !/rgba\\(0,\\s*0,\\s*0,\\s*0\\)/.test(bg)) {
      return toHex(bg, fallback);
    }
  }
  return toHex("", fallback);
}

let last = "";

export async function syncDisplayMode(): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  const { hex, luminance } = readBackground();
  const isLightBackground = luminance > 0.5;
  document.documentElement.setAttribute("data-nf-scheme", isLightBackground ? "light" : "dark");
  const signature = hex + (isLightBackground ? "-d" : "-l") + (document.body.dataset.nfFullscreen || "");
  if (signature === last) return;
  last = signature;
  try {
    await StatusBar.setStyle({ style: isLightBackground ? Style.Dark : Style.Light });
    if (!OVERLAYS && document.body.dataset.nfFullscreen !== "true") {
      await StatusBar.setBackgroundColor({ color: hex });
    } else {
      await StatusBar.setBackgroundColor({ color: "#00000000" });
    }
  } catch (e) {
    console.warn("[nf-display-mode] status bar update failed", e);
  }
  try {
    const nav = (window as any).NavigationBar;
    if (nav?.setColor) await nav.setColor({ color: hex, darkButtons: isLightBackground });
  } catch { /* NavigationBar plugin is optional */ }
}

const schedule = () => requestAnimationFrame(() => { void syncDisplayMode(); });

export async function initDisplayMode(): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  try {
    await StatusBar.setOverlaysWebView({ overlay: OVERLAYS });
  } catch (e) {
    console.warn("[nf-display-mode] overlay setup failed", e);
  }
  await syncDisplayMode();

  new MutationObserver(schedule).observe(document.body, {
    attributes: true,
    attributeFilter: ["style", "class", "data-theme", "data-nf-fullscreen"],
  });
  new MutationObserver(schedule).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["style", "class", "data-theme"],
  });

  window.matchMedia?.("(prefers-color-scheme: dark)").addEventListener?.("change", schedule);
  window.addEventListener("resize", schedule);
  window.addEventListener("orientationchange", schedule);
  window.addEventListener("popstate", schedule);

  try {
    App.addListener("appStateChange", ({ isActive }) => { if (isActive) schedule(); });
  } catch { /* @capacitor/app not available */ }
}

if (typeof window !== "undefined") {
  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", () => { void initDisplayMode(); });
  } else {
    void initDisplayMode();
  }
}
`;
}

/** Mode 4 — injects and themes the two frosted glass layers. */
export const GLASS_MODULE_TS = `// Auto-generated by NativeForge Display Mode — glassmorphism layers.
import { Capacitor } from "@capacitor/core";
import "./display-mode-glass.css";

function ensureLayer(id: string): HTMLElement {
  let el = document.getElementById(id);
  if (!el) {
    el = document.createElement("div");
    el.id = id;
    el.setAttribute("aria-hidden", "true");
    document.body.appendChild(el);
  }
  return el;
}

function applyScheme() {
  const dark = document.documentElement.getAttribute("data-nf-scheme") === "dark"
    || (window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false);
  const tint = dark ? "rgba(0, 0, 0, 0.7)" : "rgba(255, 255, 255, 0.7)";
  for (const id of ["nf-glass-top", "nf-glass-bottom"]) {
    const el = document.getElementById(id);
    if (el) el.style.backgroundColor = tint;
  }
}

export function initGlassLayers(): void {
  if (!Capacitor.isNativePlatform()) return;
  ensureLayer("nf-glass-top");
  ensureLayer("nf-glass-bottom");
  applyScheme();
  window.matchMedia?.("(prefers-color-scheme: dark)").addEventListener?.("change", applyScheme);
  new MutationObserver(applyScheme).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-nf-scheme", "class", "data-theme"],
  });
}

if (typeof window !== "undefined") {
  if (document.readyState === "loading") {
    window.addEventListener("DOMContentLoaded", initGlassLayers);
  } else {
    initGlassLayers();
  }
}
`;

/** Mode 5 — the public per-page API used by the injected hooks. */
export const PER_PAGE_API_TS = `// Auto-generated by NativeForge Display Mode — per-page full screen API.
import { Capacitor } from "@capacitor/core";
import { StatusBar, Style } from "@capacitor/status-bar";
import { syncDisplayMode } from "./display-mode";

interface Saved { paddingTop: string; paddingBottom: string; }
let saved: Saved | null = null;
let depth = 0;

/** Switch the current page to true full screen (content under both bars). */
export async function enterFullScreen(iconStyle: "LIGHT" | "DARK" = "LIGHT"): Promise<void> {
  depth += 1;
  if (depth > 1) return;
  if (!saved) {
    saved = {
      paddingTop: document.body.style.paddingTop,
      paddingBottom: document.body.style.paddingBottom,
    };
  }
  document.body.dataset.nfFullscreen = "true";
  document.body.style.paddingTop = "0px";
  document.body.style.paddingBottom = "0px";
  if (!Capacitor.isNativePlatform()) return;
  try {
    await StatusBar.setOverlaysWebView({ overlay: true });
    await StatusBar.setBackgroundColor({ color: "#00000000" });
    await StatusBar.setStyle({ style: iconStyle === "LIGHT" ? Style.Light : Style.Dark });
  } catch (e) {
    console.warn("[nf-display-mode] enterFullScreen failed", e);
  }
}

/** Restore the base display mode configured for the project. */
export async function exitFullScreen(): Promise<void> {
  depth = Math.max(0, depth - 1);
  if (depth > 0) return;
  delete document.body.dataset.nfFullscreen;
  if (saved) {
    document.body.style.paddingTop = saved.paddingTop;
    document.body.style.paddingBottom = saved.paddingBottom;
    saved = null;
  }
  await syncDisplayMode();
}

/** React helper: call inside a component that should be full screen. */
export function useFullScreenPage(iconStyle: "LIGHT" | "DARK" = "LIGHT") {
  if (typeof window === "undefined") return;
  void enterFullScreen(iconStyle);
  return () => { void exitFullScreen(); };
}
`;

/** Snippet the AI wiring step injects into detected full-screen pages. */
export const PER_PAGE_REACT_SNIPPET = `import { useEffect } from "react";
import { enterFullScreen, exitFullScreen } from "@/capacitor/display-mode-per-page";

// NativeForge Display Mode — this page renders edge to edge.
useEffect(() => {
  void enterFullScreen("LIGHT");
  return () => { void exitFullScreen(); };
}, []);
`;

export const PER_PAGE_VUE_SNIPPET = `import { onMounted, onUnmounted } from "vue";
import { enterFullScreen, exitFullScreen } from "@/capacitor/display-mode-per-page";

onMounted(() => { void enterFullScreen("LIGHT"); });
onUnmounted(() => { void exitFullScreen(); });
`;
